# Generated by Django 5.0 on 2024-01-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000000)),
                ('user_id', models.CharField(default=str, max_length=10)),
                ('currentEpisode', models.CharField(max_length=100, null=True)),
                ('content_id', models.CharField(max_length=100)),
                ('user_content_id', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(null=True, upload_to='media')),
                ('description', models.CharField(max_length=300)),
                ('episodes', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100)),
                ('typeContent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(max_length=5)),
                ('review', models.CharField(max_length=100)),
                ('content_id', models.CharField(max_length=100000)),
                ('user_content_id', models.CharField(max_length=100000)),
                ('comments_id', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
