# Generated by Django 5.0 on 2024-01-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='content',
            name='episodes',
            field=models.IntegerField(null=True),
        ),
    ]
