# Generated by Django 5.0 on 2024-01-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_alter_content_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='poster',
            field=models.ImageField(max_length=1000, null=True, upload_to='media'),
        ),
    ]
