# Generated by Django 5.0 on 2024-02-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_delete_users_remove_comments_user_content_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
