# Generated by Django 5.0 on 2024-02-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_alter_content_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
