# Generated by Django 5.0 on 2024-02-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0010_alter_content_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_id',
            field=models.IntegerField(default=0),
        ),
    ]
