# Generated by Django 5.0 on 2024-02-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0011_content_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_id',
            field=models.CharField(max_length=500),
        ),
    ]
