# Generated by Django 5.0 on 2024-02-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0012_alter_content_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_content',
            name='comments_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.comments'),
        ),
    ]
