# Generated by Django 5.0 on 2024-02-10 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0013_alter_user_content_comments_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_content',
            name='comments_id',
        ),
        migrations.AlterField(
            model_name='comments',
            name='content_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ratings.content'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
