# Generated by Django 5.0 on 2024-03-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0015_alter_content_poster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
